services:
  postgres-primary:
    image: postgres:18.2
    container_name: ecommerce-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql
      - ./docker/postgres/primary/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
      - ./docker/postgres/primary/init:/docker-entrypoint-initdb.d:ro
    command:
      - postgres
      - -c
      - wal_level=replica
      - -c
      - max_wal_senders=10
      - -c
      - max_replication_slots=10
      - -c
      - hba_file=/etc/postgresql/pg_hba.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommerce"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  postgres-replica:
    image: postgres:18.2
    container_name: ecommerce-postgres-replica
    depends_on:
      postgres-primary:
        condition: service_healthy
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
      PRIMARY_HOST: ecommerce-postgres
      REPLICATION_USER: replicator
      REPLICATION_PASSWORD: replicator_pass
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-replica-data:/var/lib/postgresql
      - ./docker/postgres/replica/start-replica.sh:/usr/local/bin/start-replica.sh:ro
    entrypoint: ["bash", "/usr/local/bin/start-replica.sh"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommerce"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped
