[project]
name = "ecommerce-product-listing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faker>=40.1.2",
    "requests>=2.32.5",
]
